### ISSUE TITLE
Availability by Servicesgroups\Hostsgroups

### ISSUE THREAD

**Issue by Azef1** [shinken-monitoring/mod-mongo-logs#7]
Hi,

Currently, the availability log store only the logs for services and hosts.
Is it possible to do the same thing but by Servicesgroups\Hostsgroups ?

thx

**Comment by maethor** [comment]
Hi,

I don't understand your question. Servicesgroups and Hostsgroups are just… groups, they don't have any state. What should we store?

**Comment by Azef1** [comment]
About servicesgroups state:
I created some services inside a servicegroup. In Nagvis i can add a servicegroups icon,  this icon change state if there are a service who change state. So, for me a servicesgroup has a state.

Eg: 
WebServer (servicegroup)
|__NGINX (service)
|__PHP (service)
|__MySQL (service)

In Nagvis i can add a icon represent the servicegroup WebServer. If PHP become critical the WebServer icon become red (critical).
Perhaps, Nagvis compute himself the servicegroup's state.

So, my question is: Is it possible to log the availability for a servicegroup ? Here, if PHP become critical during 2 hours, the availability for servicegroup WebServer will be "Daily_2(critical)=2hours"
Currently, we have only the availability for each services (NGINX,PHP,MYSQL) separately and we haven't a aggregate availability by servicegroup.
The goal: Is to have the SLA of WebServer.

Sorry, for my bad english

**Comment by maethor** [comment]
OK, I understand.

Shinken is not Nagvis, and it don't work like this. A service group is just a group of services, it's pretty useless (except [advanced stuff](http://shinken.readthedocs.org/en/latest/07_advanced/objecttricks.html#id7), but even this example, you should not do it like that). I insist, Shinken servicegroups do not have a state.

In shinken, if you want to do something like this, you have to use [business rules](http://shinken.readthedocs.org/en/latest/06_medium/business-rules.html) which are way more powerful (because they can describe complex aggregation rules). And then, you can do basic SLA on the business rules (they are just services).

Also, I would suggest that instead of doing SLA on something complex like that, you can just do it on the application hosted on this stack. Choose a URL soliciting both PHP and MySQL, and you are good to go.

**Comment by mohierf** [comment]
@maethor, nice idea to propose business rules :+1: 

I close this issue.

**Comment by Azef1** [comment]
Thank you, business rules correspond exactly to my needs. I now understand better hostgroup and servicegroup. Nagvis misled me
